#pragma once
#define MAX_LOADSTRING 100
#define ID_TOOLBOX 75
#define ID_GROUP1 76
#define ID_GROUP2 77
#define ID_GROUP3 78
#define ID_GROUP4 79
#define ID_GROUP5 27
#define ID_GROUP6 84
#define ID_LINE 60
#define ID_SHAPE_CIRCLE 61
#define ID_SHAPE_RECTANGLE 62
#define ID_SHAPE_ISOSCELES_TRIANGLE 63
#define ID_SHAPE_TRIANGLE 64
#define ID_SHAPE_QUADRILATERAL 65 
#define ID_SHAPE_PENTAGON 66
#define ID_SHAPE_HEXAGON 67
#define ID_SHAPE_FORWARD_ARROW 68 
#define ID_SHAPE_BACK_ARROW 69
#define ID_SHAPE_UP_ARROW 70
#define ID_SHAPE_DOWN_ARROW 71
#define ID_SHAPE_FOUR_POINT_STAR 72
#define ID_SHAPE_FIVE_POINT_STAR 73
#define ID_SHAPE_SIX_POINT_STAR 74

#define ID_SHAPE_LIGHTNING 91
#define ID_SHAPE_ROUND_RECT 92

#define ID_PENSIZE1 22
#define ID_PENSIZE2 23
#define ID_PENSIZE3 24
#define ID_PENSIZE4 25
#define ID_PENSIZE5 26

#define ID_COLOR1 28
#define ID_COLOR2 29
#define ID_COLOR_NUMBER1 30
#define ID_COLOR_NUMBER2 31
#define ID_COLOR_NUMBER_SELECT1 32
#define ID_COLOR_NUMBER_SELECT2 33
#define ID_COLOR_WHITE 34
#define ID_COLOR_LIGHTGRAY 35
#define ID_COLOR_LIGHTBROWN 36
#define ID_COLOR_PINK 37
#define ID_COLOR_LIGHTORANGE 38
#define ID_COLOR_LIGHTYELLOW 39
#define ID_COLOR_LIGHTGREEN 40
#define ID_COLOR_LIGHTAQUA 42
#define ID_COLOR_LIGHTBLUE 43
#define ID_COLOR_LIGHTPURPLE 44

#define ID_COLOR_BLACK 45
#define ID_COLOR_DARKGRAY 46
#define ID_COLOR_DARKBROWN 47
#define ID_COLOR_RED 48
#define ID_COLOR_DARKORANGE 49
#define ID_COLOR_DARKYELLOW 50
#define ID_COLOR_DARKGREEN 52
#define ID_COLOR_DARKAQUA 53
#define ID_COLOR_DARKBLUE 54
#define ID_COLOR_DARKPURPLE 55

#define ID_SETCOLORPEN 56
#define ID_SETBACKGROUND 57
#define ID_BACKGROUND 58
#define ID_LABLE_CHOOSE 59
#define ID_LABLE_COLOR 80
#define ID_STATUS_BAR 83
#define ID_PEN_STYLE1 85
#define ID_PEN_STYLE2 86
#define ID_PEN_STYLE3 87
#define ID_PEN_STYLE4 88
#define ID_CHOOSE_COLOR 89
//#define ID_DRAW_AREA 90

